# Logisitc Regression Model

## Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

## Load the preprocessed data

In [2]:
df_preprocessed = pd.read_csv('data/processed/Laliga_fixtures_preprocessed.csv')

In [3]:
df_preprocessed.head()

Month  Day  Time_Sin  Time_Cos  Wk  Home Position  Home_code_0  \
0      8    4 -0.831470  0.555570   1              0            0   
1      8    4 -0.442289  0.896873   1              0            1   
2      8    5 -0.997859  0.065403   1              0            0   
3      8    5 -0.831470  0.555570   1              0            1   
4      8    5 -0.442289  0.896873   1              0            1   

   Home_code_1  Home_code_2  Home_code_3  ...  G_Home  G_Away  xG_Away  \
0            1            1            1  ...       1       0      1.1   
1            0            0            0  ...       1       0      0.2   
2            1            0            1  ...       2       3      2.1   
3            0            0            1  ...       2       2      0.7   
4            0            0            0  ...       1       1      1.3   

   Away_code_0  Away_code_1  Away_code_2  Away_code_3  Away_code_4  \
0            0            0            0            0            0   
1            0            0            0            0            1   
2            0            0            0            1            0   
3            0            0            0            1            1   
4            0            0            1            0            0   

   Away Position  Target  
0              0       1  
1              0       1  
2              0       0  
3              0       0  
4              0       0  

[5 rows x 22 columns]

In [4]:
df_preprocessed.describe()

Month          Day      Time_Sin     Time_Cos          Wk  \
count  3040.000000  3040.000000  3.040000e+03  3040.000000  3040.00000   
mean      6.326316     4.571053 -7.540947e-01     0.111313    19.50000   
std       3.719885     1.782576  2.288625e-01     0.605566    10.96766   
min       1.000000     0.000000 -1.000000e+00    -1.000000     1.00000   
25%       3.000000     4.000000 -9.469301e-01    -0.442289    10.00000   
50%       5.000000     5.000000 -7.518398e-01     0.130526    19.50000   
75%      10.000000     6.000000 -7.071068e-01     0.707107    29.00000   
max      12.000000     6.000000  1.224647e-16     0.923880    38.00000   

       Home Position  Home_code_0  Home_code_1  Home_code_2  Home_code_3  ...  \
count    3040.000000   3040.00000  3040.000000  3040.000000  3040.000000  ...   
mean       10.319737      0.38750     0.375000     0.400000     0.550000  ...   
std         5.945547      0.48726     0.484203     0.489979     0.497576  ...   
min         0.000000      0.00000     0.000000     0.000000     0.000000  ...   
25%         5.000000      0.00000     0.000000     0.000000     0.000000  ...   
50%        10.000000      0.00000     0.000000     0.000000     1.000000  ...   
75%        15.000000      1.00000     1.000000     1.000000     1.000000  ...   
max        20.000000      1.00000     1.000000     1.000000     1.000000  ...   

            G_Home       G_Away      xG_Away  Away_code_0  Away_code_1  \
count  3040.000000  3040.000000  3040.000000   3040.00000  3040.000000   
mean      1.452303     1.116118     1.110033      0.38750     0.375000   
std       1.244016     1.092318     0.704539      0.48726     0.484203   
min       0.000000     0.000000     0.000000      0.00000     0.000000   
25%       1.000000     0.000000     0.600000      0.00000     0.000000   
50%       1.000000     1.000000     1.000000      0.00000     0.000000   
75%       2.000000     2.000000     1.500000      1.00000     1.000000   
max       8.000000     7.000000     5.000000      1.00000     1.000000   

       Away_code_2  Away_code_3  Away_code_4  Away Position       Target  
count  3040.000000  3040.000000  3040.000000    3040.000000  3040.000000  
mean      0.400000     0.550000     0.456250      10.127632     0.448026  
std       0.489979     0.497576     0.498164       5.920736     0.497373  
min       0.000000     0.000000     0.000000       0.000000     0.000000  
25%       0.000000     0.000000     0.000000       5.000000     0.000000  
50%       0.000000     1.000000     0.000000      10.000000     0.000000  
75%       1.000000     1.000000     1.000000      15.000000     1.000000  
max       1.000000     1.000000     1.000000      20.000000     1.000000  

[8 rows x 22 columns]

## Exploring the targets

In [5]:
df_preprocessed['Target'].value_counts()

Target
0    1678
1    1362
Name: count, dtype: int64

In [6]:
df_preprocessed['Target'].sum() / len(df_preprocessed['Target'])

np.float64(0.44802631578947366)

## Selecting Inputs

In [7]:
targets = df_preprocessed.iloc[:, -1]

In [8]:
unscaled_inputs = df_preprocessed.iloc[:, :-1]
unscaled_inputs = unscaled_inputs.drop(columns = ['G_Home', 'G_Away'])
unscaled_inputs.head(5)

Month  Day  Time_Sin  Time_Cos  Wk  Home Position  Home_code_0  \
0      8    4 -0.831470  0.555570   1              0            0   
1      8    4 -0.442289  0.896873   1              0            1   
2      8    5 -0.997859  0.065403   1              0            0   
3      8    5 -0.831470  0.555570   1              0            1   
4      8    5 -0.442289  0.896873   1              0            1   

   Home_code_1  Home_code_2  Home_code_3  Home_code_4  xG_Home  xG_Away  \
0            1            1            1            1      1.3      1.1   
1            0            0            0            1      1.4      0.2   
2            1            0            1            0      1.8      2.1   
3            0            0            1            1      2.2      0.7   
4            0            0            0            0      2.4      1.3   

   Away_code_0  Away_code_1  Away_code_2  Away_code_3  Away_code_4  \
0            0            0            0            0            0   
1            0            0            0            0            1   
2            0            0            0            1            0   
3            0            0            0            1            1   
4            0            0            1            0            0   

   Away Position  
0              0  
1              0  
2              0  
3              0  
4              0

In [9]:
unscaled_inputs.columns.values

array(['Month', 'Day', 'Time_Sin', 'Time_Cos', 'Wk', 'Home Position',
       'Home_code_0', 'Home_code_1', 'Home_code_2', 'Home_code_3',
       'Home_code_4', 'xG_Home', 'xG_Away', 'Away_code_0', 'Away_code_1',
       'Away_code_2', 'Away_code_3', 'Away_code_4', 'Away Position'],
      dtype=object)

In [10]:
columns_as_inputs = ['Time_Sin', 'Time_Cos', 'Wk', 'Home Position',
       'Home_code_0', 'Home_code_1', 'Home_code_2', 'Home_code_3',
       'Home_code_4', 'xG_Home', 'xG_Away', 'Away_code_0', 'Away_code_1',
       'Away_code_2', 'Away_code_3', 'Away_code_4', 'Away Position']

In [11]:
unscaled_inputs = unscaled_inputs[columns_as_inputs]

## Standardization

In [12]:
columns_to_standardize = ['xG_Home', 'xG_Away']

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
unscaled_inputs[columns_to_standardize] = scaler.fit_transform(unscaled_inputs[columns_to_standardize])

In [16]:
scaled_inputs = unscaled_inputs.copy()

In [17]:
scaled_inputs

Time_Sin  Time_Cos  Wk  Home Position  Home_code_0  Home_code_1  \
0    -0.831470  0.555570   1              0            0            1   
1    -0.442289  0.896873   1              0            1            0   
2    -0.997859  0.065403   1              0            0            1   
3    -0.831470  0.555570   1              0            1            0   
4    -0.442289  0.896873   1              0            1            0   
...        ...       ...  ..            ...          ...          ...   
3035 -0.707107  0.707107  38              8            1            0   
3036 -0.896873 -0.442289  38              2            0            0   
3037 -0.707107  0.707107  38              4            0            1   
3038 -0.500000 -0.866025  38             15            1            0   
3039 -0.896873 -0.442289  38              5            0            1   

      Home_code_2  Home_code_3  Home_code_4   xG_Home   xG_Away  Away_code_0  \
0               1            1            1 -0.197333 -0.014243            0   
1               0            0            1 -0.074202 -1.291884            0   
2               0            1            0  0.418321  1.405359            0   
3               0            1            1  0.910844 -0.582083            0   
4               0            0            0  1.157105  0.269678            0   
...           ...          ...          ...       ...       ...          ...   
3035            1            1            0  0.910844 -0.724043            1   
3036            1            1            1  1.403367 -0.440123            0   
3037            1            1            0 -0.320464  3.392801            0   
3038            0            1            1 -1.798033  2.257120            0   
3039            0            0            0 -0.443595  0.553598            1   

      Away_code_1  Away_code_2  Away_code_3  Away_code_4  Away Position  
0               0            0            0            0              0  
1               0            0            0            1              0  
2               0            0            1            0              0  
3               0            0            1            1              0  
4               0            1            0            0              0  
...           ...          ...          ...          ...            ...  
3035            1            0            0            1             10  
3036            0            0            1            0             11  
3037            1            0            1            1              1  
3038            0            0            1            1              3  
3039            0            0            0            0             16  

[3040 rows x 17 columns]

In [18]:
scaled_inputs.shape

(3040, 17)

In [19]:
scaled_inputs.columns.values

array(['Time_Sin', 'Time_Cos', 'Wk', 'Home Position', 'Home_code_0',
       'Home_code_1', 'Home_code_2', 'Home_code_3', 'Home_code_4',
       'xG_Home', 'xG_Away', 'Away_code_0', 'Away_code_1', 'Away_code_2',
       'Away_code_3', 'Away_code_4', 'Away Position'], dtype=object)

## Splitting the data into training and testing, and shuffling

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=20)

In [22]:
print(x_train.shape, y_train.shape)

(2432, 17) (2432,)


In [23]:
print(x_test.shape, y_test.shape)

(608, 17) (608,)


## Logistic Regression with SK-Learn

### Training

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [25]:
reg = LogisticRegression(max_iter=1000)

In [26]:
reg.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [27]:
reg.score(x_train, y_train)

0.7228618421052632

### Intercepts and Coefficients

In [28]:
reg.intercept_

array([-0.20983109])

In [29]:
reg.coef_

array([[ 0.20578158, -0.05075497,  0.00848875, -0.02828362, -0.22842495,
        -0.24094   , -0.18450171,  0.18133406,  0.27788528,  0.79654975,
        -0.61744104,  0.04480233,  0.18894248,  0.04878099, -0.24769848,
        -0.17178751,  0.0343737 ]])

In [30]:
feature_name = unscaled_inputs.columns.values

In [31]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0        Time_Sin     0.205782
1        Time_Cos    -0.050755
2              Wk     0.008489
3   Home Position    -0.028284
4     Home_code_0    -0.228425
5     Home_code_1    -0.240940
6     Home_code_2    -0.184502
7     Home_code_3     0.181334
8     Home_code_4     0.277885
9         xG_Home     0.796550
10        xG_Away    -0.617441
11    Away_code_0     0.044802
12    Away_code_1     0.188942
13    Away_code_2     0.048781
14    Away_code_3    -0.247698
15    Away_code_4    -0.171788
16  Away Position     0.034374

In [32]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0       Intercept    -0.209831
1        Time_Sin     0.205782
2        Time_Cos    -0.050755
3              Wk     0.008489
4   Home Position    -0.028284
5     Home_code_0    -0.228425
6     Home_code_1    -0.240940
7     Home_code_2    -0.184502
8     Home_code_3     0.181334
9     Home_code_4     0.277885
10        xG_Home     0.796550
11        xG_Away    -0.617441
12    Away_code_0     0.044802
13    Away_code_1     0.188942
14    Away_code_2     0.048781
15    Away_code_3    -0.247698
16    Away_code_4    -0.171788
17  Away Position     0.034374

In [33]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [34]:
summary_table

Feature name  Coefficient  Odds_ratio
0       Intercept    -0.209831    0.810721
1        Time_Sin     0.205782    1.228485
2        Time_Cos    -0.050755    0.950512
3              Wk     0.008489    1.008525
4   Home Position    -0.028284    0.972113
5     Home_code_0    -0.228425    0.795786
6     Home_code_1    -0.240940    0.785889
7     Home_code_2    -0.184502    0.831519
8     Home_code_3     0.181334    1.198816
9     Home_code_4     0.277885    1.320335
10        xG_Home     0.796550    2.217875
11        xG_Away    -0.617441    0.539323
12    Away_code_0     0.044802    1.045821
13    Away_code_1     0.188942    1.207971
14    Away_code_2     0.048781    1.049990
15    Away_code_3    -0.247698    0.780595
16    Away_code_4    -0.171788    0.842158
17  Away Position     0.034374    1.034971

In [36]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
10        xG_Home     0.796550    2.217875
9     Home_code_4     0.277885    1.320335
1        Time_Sin     0.205782    1.228485
13    Away_code_1     0.188942    1.207971
8     Home_code_3     0.181334    1.198816
14    Away_code_2     0.048781    1.049990
12    Away_code_0     0.044802    1.045821
17  Away Position     0.034374    1.034971
3              Wk     0.008489    1.008525
4   Home Position    -0.028284    0.972113
2        Time_Cos    -0.050755    0.950512
16    Away_code_4    -0.171788    0.842158
7     Home_code_2    -0.184502    0.831519
0       Intercept    -0.209831    0.810721
5     Home_code_0    -0.228425    0.795786
6     Home_code_1    -0.240940    0.785889
15    Away_code_3    -0.247698    0.780595
11        xG_Away    -0.617441    0.539323

### Testing

In [37]:
reg.score(x_test, y_test)

0.6875

In [38]:
predict_proba = reg.predict_proba(x_test)
predict_proba

array([[0.10267145, 0.89732855],
       [0.24410408, 0.75589592],
       [0.74152446, 0.25847554],
       ...,
       [0.5383773 , 0.4616227 ],
       [0.30690103, 0.69309897],
       [0.51922704, 0.48077296]])

In [39]:
predict_proba.shape

(608, 2)

In [40]:
predict_proba[:, 1]

array([0.89732855, 0.75589592, 0.25847554, 0.60315429, 0.74913403,
       0.25752819, 0.54428443, 0.64277321, 0.13022363, 0.55786072,
       0.77789241, 0.09648763, 0.92234722, 0.36524353, 0.12753114,
       0.01541962, 0.91260623, 0.43036646, 0.31971797, 0.08468654,
       0.11330303, 0.28897303, 0.59155109, 0.27937504, 0.44620039,
       0.12852871, 0.40962694, 0.44992788, 0.41727898, 0.20269346,
       0.35792248, 0.37121516, 0.83951233, 0.34569772, 0.7014617 ,
       0.23872408, 0.72136633, 0.71637113, 0.36301083, 0.47294405,
       0.28005177, 0.10482815, 0.14034977, 0.39954973, 0.80406002,
       0.77145279, 0.89381621, 0.34599444, 0.56901186, 0.73736978,
       0.86049939, 0.41333026, 0.36285665, 0.93157353, 0.73438386,
       0.30931573, 0.07038905, 0.5774973 , 0.5505822 , 0.88354305,
       0.87436597, 0.30534171, 0.78227699, 0.29230916, 0.17970682,
       0.92145853, 0.31341321, 0.1734378 , 0.69336911, 0.06760503,
       0.6319574 , 0.18135397, 0.40306144, 0.02541953, 0.14412

## Saving the model

In [43]:
import pickle

In [44]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [45]:
with open('scaler', 'wb') as file:
    pickle.dump(scaler, file)